# Generated by Django 4.1.4 on 2022-12-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.pnj', upload_to='profile_images'),
        ),
    ]
