# Generated by Django 4.1.4 on 2022-12-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
