# Generated by Django 4.1.4 on 2023-01-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
